person = input('A person: ')
noun = input('A noun: ')
verb = input('A verb: ')
print('One day,',person,'went to a party.')
print('A big mean',noun,'stood in their way.')
print('So',person,'did a',verb,'and was able to get past!')
